import {Gasoek_One} from 'next/font/google';
import localFont from 'next/font/local';

import Header from './components/common/Header';
import Providers from './utils/provider';

import type {Metadata} from 'next';

import './globals.css';

// const inter = Inter({subsets: ['latin']});

const myFont = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
});

const gasoek = Gasoek_One({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-gasoek',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="ko">
      <body className={`${myFont.className} ${gasoek.variable}`}>
        <Providers>
          <Header />
          <div className="w-full max-w-[1080px] mx-auto mt-40 px-4 md:px-8 xl:px-10 min-h-[72vh]">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
